import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../models/match_score_result.dart';

/// FR-14 / S-16 — generates a PDF of the Skill Gap Roadmap (Section
/// 12.5), mirroring the Gantt chart shown on-screen (S-13): one section
/// per semester, each gap listed with its priority and remediation
/// suggestion.
class RoadmapPdfService {
  const RoadmapPdfService._();

  static Future<List<int>> generate({
    required String studentName,
    required String jobTitle,
    required List<RoadmapEntry> roadmap,
  }) async {
    final doc = pw.Document();

    final bySemester = <int, List<RoadmapEntry>>{};
    for (final entry in roadmap) {
      bySemester.putIfAbsent(entry.semesterNumber, () => []).add(entry);
    }
    final semesterNumbers = bySemester.keys.toList()..sort();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Skill Gap Roadmap', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 4),
                pw.Text('$studentName — Target role: $jobTitle', style: const pw.TextStyle(fontSize: 12)),
                pw.SizedBox(height: 2),
                pw.Text(
                  'Generated by Talent Tracker AI - Daffodil International University',
                  style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 12),
          if (roadmap.isEmpty)
            pw.Text('No open skill gaps for this role — every critical-path course is complete.')
          else
            for (final semNum in semesterNumbers) ...[
              pw.SizedBox(height: 10),
              pw.Text('Semester $semNum', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 6),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
                columnWidths: const {
                  0: pw.FlexColumnWidth(2),
                  1: pw.FlexColumnWidth(1),
                  2: pw.FlexColumnWidth(3),
                },
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                    children: [
                      _cell('Gap', bold: true),
                      _cell('Priority', bold: true),
                      _cell('Recommended action', bold: true),
                    ],
                  ),
                  for (final entry in bySemester[semNum]!)
                    pw.TableRow(
                      children: [
                        _cell(entry.gap.label),
                        _cell(_priorityLabel(entry.gap.weight)),
                        _cell(entry.gap.remediation),
                      ],
                    ),
                ],
              ),
            ],
        ],
      ),
    );

    return doc.save();
  }

  static pw.Widget _cell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(fontSize: 10, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal),
      ),
    );
  }

  /// Mirrors SkillGapRoadmapScreen's priority colour thresholds (Section
  /// 12.5) so the PDF and the on-screen Gantt chart agree.
  static String _priorityLabel(double weight) {
    if (weight >= 0.70) return 'HIGH';
    if (weight >= 0.40) return 'MEDIUM';
    return 'LOW';
  }
}
